In [1]:
import numpy as np

In [2]:
alphabet = list(map(lambda x: x, 
                    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 !@#$%^&*()_+<>.,"))
print(alphabet)
length = len(alphabet)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ' ', '!', '@', '#', '$', '%', '^', '&', '*', '(', ')', '_', '+', '<', '>', '.', ',']


In [3]:
# _str = "Hello, World!"
_str = "I Love You."
binary_rep = []
for i in _str:
    binary_rep.append(bin(alphabet.index(i)))
print(binary_rep)

['0b100010', '0b111110', '0b100101', '0b1110', '0b10101', '0b100', '0b111110', '0b110010', '0b1110', '0b10100', '0b1001101']


In [4]:
def block_creator(binary_code):
    # padding
    binary_code = binary_code[2:]
    length = len(binary_code)
    for i in range(length, 11):
        binary_code = "0" + binary_code
    # print(binary_code)
    # print("****************************")
    # end of padding
    places = [[0,3], [1,1], [1,2], [1,3], [2,1], [2,2], [2,3], [3,0], [3,1], [3,2], [3,3]]
    block = np.zeros((4,4), np.int8)
    for index, value in enumerate(binary_code):
        row, col = places[index]
        block[row][col] = value
    # print(block)
    # print("****************************")

    if (np.count_nonzero(block[:, 1]) + np.count_nonzero(block[:, 3])) % 2 == 1:
        block[0][1] = 1
    if (np.count_nonzero(block[:, 2]) + np.count_nonzero(block[:, 3])) % 2 == 1:
        block[0][2] = 1
    if (np.count_nonzero(block[1]) + np.count_nonzero(block[3])) % 2 == 1:
        block[1][0] = 1
    if (np.count_nonzero(block[2]) + np.count_nonzero(block[3])) % 2 == 1:
        block[2][0] = 1
    if np.count_nonzero(block) % 2:
        block[0][0] = 1
    print(block)
    print("****************************")
    return block

In [5]:
# binary_rep[i] = block_creator(binary_rep[i])
binary_str = ""
for i in range(len(binary_rep)):
    _list = (block_creator(binary_rep[i])).flatten(order="C")
    _list = _list.tolist()
    binary_str += "".join([str(i) for i in _list])

[[1 0 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [0 0 1 0]]
****************************
[[0 0 1 0]
 [1 0 0 0]
 [1 0 1 1]
 [1 1 1 0]]
****************************
[[0 0 0 0]
 [0 0 0 0]
 [1 0 1 0]
 [0 1 0 1]]
****************************
[[1 1 1 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 1 1 0]]
****************************
[[1 1 0 0]
 [0 0 0 0]
 [1 0 0 1]
 [0 1 0 1]]
****************************
[[0 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]]
****************************
[[0 0 1 0]
 [1 0 0 0]
 [1 0 1 1]
 [1 1 1 0]]
****************************
[[1 1 1 0]
 [1 0 0 0]
 [1 0 1 1]
 [0 0 1 0]]
****************************
[[1 1 1 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 1 1 0]]
****************************
[[0 0 1 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 1 0 0]]
****************************
[[1 1 1 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 1 0 1]]
****************************


In [6]:
with open("data.txt", "w") as file:
    file.write(binary_str)