In [1]:
import numpy as np

In [2]:
with open("data.txt", "r") as file:
    data = file.read()
print(data)

10001000001000100010100010111110000000001010010111101000100011101100000010010101010010001000010000101000101111101110100010110010111010001000111000101000000101001110100001001101


In [3]:
binary_rep = []
for i in range(0, len(data), 16):
    binary_rep.append(data[i:i+16])
print(binary_rep)

['1000100000100010', '0010100010111110', '0000000010100101', '1110100010001110', '1100000010010101', '0100100010000100', '0010100010111110', '1110100010110010', '1110100010001110', '0010100000010100', '1110100001001101']


In [4]:
def block_creator(str_rep):
    _list = list(map(lambda x: int(x), str_rep))
    block = np.array(_list)
    block = block.reshape((4,4))
    error = [False, False, False, False]
    if (np.count_nonzero(block[1:, 1]) + np.count_nonzero(block[:, 3])) % 2 != block[0][1]:
        error[0] = True
    if (np.count_nonzero(block[1:, 2]) + np.count_nonzero(block[:, 3])) % 2 != block[0][2]:
        error[1] = True
    if (np.count_nonzero(block[1][1:]) + np.count_nonzero(block[3])) % 2 != block[1][0]:
        error[2] = True
    if (np.count_nonzero(block[2][1:]) + np.count_nonzero(block[3])) % 2 != block[2][0]:
        error[3] = True
        
    if any(error):
        col_error = None
        row_error = None
        if error[0] and error[1]:
            col_error = 3
        elif error[0] and not error[1]:
            col_error = 1
        elif not error[0] and error[1]:
            col_error = 2
        elif not error[0] and not error[1]:
            col_error = 0
    
        if error[2] and error[3]:
            row_error = 3
        elif error[2] and not error[3]:
            row_error = 1
        elif not error[2] and error[3]:
            row_error = 2
        elif not error[2] and not error[3]:
            row_error = 0

        block[row_error][col_error] += 1
        block[row_error][col_error] %= 2
    print(block)
    print("**************")

    places = [[0,3], [1,1], [1,2], [1,3], [2,1], [2,2], [2,3], [3,0], [3,1], [3,2], [3,3]]
    _str = ""
    for row,col in places:
        _str+=str(block[row][col])
    _str = int(_str)
    _str = "0b" + str(_str)
    return _str

In [5]:
for i in range(len(binary_rep)):
    binary_rep[i] = int(block_creator(binary_rep[i]), 2)
print(binary_rep)

[[1 0 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [0 0 1 0]]
**************
[[0 0 1 0]
 [1 0 0 0]
 [1 0 1 1]
 [1 1 1 0]]
**************
[[0 0 0 0]
 [0 0 0 0]
 [1 0 1 0]
 [0 1 0 1]]
**************
[[1 1 1 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 1 1 0]]
**************
[[1 1 0 0]
 [0 0 0 0]
 [1 0 0 1]
 [0 1 0 1]]
**************
[[0 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]]
**************
[[0 0 1 0]
 [1 0 0 0]
 [1 0 1 1]
 [1 1 1 0]]
**************
[[1 1 1 0]
 [1 0 0 0]
 [1 0 1 1]
 [0 0 1 0]]
**************
[[1 1 1 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 1 1 0]]
**************
[[0 0 1 0]
 [1 0 0 0]
 [0 0 0 1]
 [0 1 0 0]]
**************
[[1 1 1 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 1 0 1]]
**************
[34, 62, 37, 14, 21, 4, 62, 50, 14, 20, 77]


In [6]:
alphabet = list(map(lambda x: x, 
                    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 !@#$%^&*()_+<>.,"))

In [7]:
original_data = ""
for i in binary_rep:
    original_data += alphabet[i]
print(original_data)

I Love You.
